### PR TITLE
remove piracy overload on 1.4

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
@KristofferC 1.4 is the correct bound?

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Fixes https://github.com/JuliaDiffEq/DiffEqBase.jl/issues/410

**Comment by KristofferC** [comment]
Not really, it is better to use `contrib/commit-name.sh` to get the exact version.

**Comment by ChrisRackauckas** [comment]
I'll find out how to run that some day, but at least this is better than nothing.

**Comment by ChrisRackauckas** [comment]
The change is at least going into 1.4 and not 1.5 or a 1.3.x, right?

**Comment by KristofferC** [comment]
This will still error on all RCs now.

**Pull request merged**
