### PR TITLE
Allso setting both jac_prototype and sparsity

### PR DESCRIPTION
**Pull request by mauro3**
Needed to make the last iteration of https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/1054 work.

### CODE REVIEW

**Comment by mauro3** [comment]
@ChrisRackauckas: presumably the positional constructors of `ODEFunction` and friends are not part of the public API?  Otherwise this PR would have been breaking.

Also, does this need updates in other DiffEq packages too?

**Comment by mauro3** [comment]
Searching for "sparsity", I found a few needing updates:
- https://github.com/JuliaDiffEq/DelayDiffEq.jl/blob/15764865c86d8e258fecd8e9df303f84c965b5e2/src/functionwrapper.jl#L27
- https://github.com/JuliaDiffEq/DiffEqDocs.jl/blob/22ee8499aeb1fd946b6623bf7c40c5ec0a32e668/docs/src/tutorials/advanced_ode_example.md#speeding-up-jacobian-calculations
- https://github.com/JuliaDiffEq/StochasticDiffEq.jl/blob/9df57b1900df1051f77e111661cd5335a70c79ba/src/derivative_wrappers.jl (several places)

**Comment by ChrisRackauckas** [comment]
@mauro3 I did the DelayDiffEq one: could you take the StochasticDiffEq one? It should be about the same as here. In fact, we should sooner or later set StochasticDiffEq to just use this part of OrdinaryDiffEq, but that's a larger ordeal.

**Comment by ChrisRackauckas** [comment]
yeah the positional constructors are just for `remake`, so it's not public.

**Comment by mauro3** [comment]
There is also DiffEqSensitivity
https://travis-ci.org/JuliaDiffEq/OrdinaryDiffEq.jl/jobs/659059359?utm_medium=notification&utm_source=github_status
with error `LoadError: type ODEForwardSensitivityFunction has no field sparsity`

**Pull request merged**
