### PR TITLE
Add MKLPardiso linear solver

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
```julia
using OrdinaryDiffEq

const N = 32
const xyd_brusselator = range(0,stop=1,length=N)
brusselator_f(x, y, t) = (((x-0.3)^2 + (y-0.6)^2) <= 0.1^2) * (t >= 1.1) * 5.
limit(a, N) = a == N+1 ? 1 : a == 0 ? N : a
function brusselator_2d_loop(du, u, p, t)
  A, B, alpha, dx = p
  alpha = alpha/dx^2
  @inbounds for I in CartesianIndices((N, N))
    i, j = Tuple(I)
    x, y = xyd_brusselator[I[1]], xyd_brusselator[I[2]]
    ip1, im1, jp1, jm1 = limit(i+1, N), limit(i-1, N), limit(j+1, N), limit(j-1, N)
    du[i,j,1] = alpha*(u[im1,j,1] + u[ip1,j,1] + u[i,jp1,1] + u[i,jm1,1] - 4u[i,j,1]) +
                B + u[i,j,1]^2*u[i,j,2] - (A + 1)*u[i,j,1] + brusselator_f(x, y, t)
    du[i,j,2] = alpha*(u[im1,j,2] + u[ip1,j,2] + u[i,jp1,2] + u[i,jm1,2] - 4u[i,j,2]) +
                A*u[i,j,1] - u[i,j,1]^2*u[i,j,2]
    end
end
p = (3.4, 1., 10., step(xyd_brusselator))

function init_brusselator_2d(xyd)
  N = length(xyd)
  u = zeros(N, N, 2)
  for I in CartesianIndices((N, N))
    x = xyd[I[1]]
    y = xyd[I[2]]
    u[I,1] = 22*(y*(1-y))^(3/2)
    u[I,2] = 27*(x*(1-x))^(3/2)
  end
  u
end
u0 = init_brusselator_2d(xyd_brusselator)

using SparsityDetection, SparseArrays
input = rand(32,32,2)
output = similar(input)
sparsity_pattern = sparsity!(brusselator_2d_loop,output,input,p,0.0)
jac_sparsity = Float64.(sparse(sparsity_pattern))

using SparseDiffTools
colorvec = matrix_colors(jac_sparsity)
@show maximum(colorvec) # maximum(colorvec) = 12

f = ODEFunction(brusselator_2d_loop;jac_prototype=jac_sparsity,
                                    colorvec=colorvec)
prob_ode_brusselator_2d_sparse = ODEProblem(f,
                                     init_brusselator_2d(xyd_brusselator),
                                     (0.,11.5),p)

using BenchmarkTools
@btime solve(prob_ode_brusselator_2d_sparse,Rodas5(),save_everystep=false)

import Pardiso
@btime solve(prob_ode_brusselator_2d_sparse,Rodas5(linsolve = DiffEqBase.MKLPardisoFactorize()),save_everystep=false)
```

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
```
  1.170 s (17411 allocations: 412.78 MiB)
  1.605 s (29696 allocations: 149.69 MiB)
```

doesn't seem to be faster.

**Comment by ViralBShah** [comment]
What are the matrix sizes?

**Comment by ChrisRackauckas** [comment]
2048×2048 SparseMatrixCSC{Bool,Int64} with 12288 stored entries

**Comment by ViralBShah** [comment]
That's probably too small to tell from. Sparse matrix should probably be much larger (say 100kx100k).

**Comment by ChrisRackauckas** [comment]
```julia
@btime solve(prob_ode_brusselator_2d_sparse,TRBDF2(),save_everystep=false)
@btime solve(prob_ode_brusselator_2d_sparse,TRBDF2(linsolve = DiffEqBase.MKLPardisoFactorize()),save_everystep=false)

@btime solve(prob_ode_brusselator_2d_sparse,KenCarp4(),save_everystep=false)
@btime solve(prob_ode_brusselator_2d_sparse,KenCarp4(linsolve = DiffEqBase.MKLPardisoFactorize()),save_everystep=false)

using Sundials
@btime solve(prob_ode_brusselator_2d_sparse,CVODE_BDF(linear_solver=:GMRES),save_everystep=false)
```

```
  TRBDF2: 1.053 s (18236 allocations: 343.76 MiB)
  TRBDF2 Pardiso: 474.382 ms (17009 allocations: 71.51 MiB)
  Sundials (Iterative Solver): 364.546 ms (61058 allocations: 3.63 MiB)
  KenCarp4: 1.581 s (22514 allocations: 377.69 MiB)
  KenCarp4 Pardiso: 544.636 ms (20317 allocations: 96.41 MiB)
```

On this kind of PDE, using an iterative solver is just better, so our default solver (SuiteSparse) and Pardiso lose out to the iterative solver.

**Comment by ChrisRackauckas** [comment]
Larger PDEs change this around. Here's with N=128:

```julia
using OrdinaryDiffEq

const N = 128
const xyd_brusselator = range(0,stop=1,length=N)
brusselator_f(x, y, t) = (((x-0.3)^2 + (y-0.6)^2) <= 0.1^2) * (t >= 1.1) * 5.
limit(a, N) = a == N+1 ? 1 : a == 0 ? N : a
function brusselator_2d_loop(du, u, p, t)
  A, B, alpha, dx = p
  alpha = alpha/dx^2
  @inbounds for I in CartesianIndices((N, N))
    i, j = Tuple(I)
    x, y = xyd_brusselator[I[1]], xyd_brusselator[I[2]]
    ip1, im1, jp1, jm1 = limit(i+1, N), limit(i-1, N), limit(j+1, N), limit(j-1, N)
    du[i,j,1] = alpha*(u[im1,j,1] + u[ip1,j,1] + u[i,jp1,1] + u[i,jm1,1] - 4u[i,j,1]) +
                B + u[i,j,1]^2*u[i,j,2] - (A + 1)*u[i,j,1] + brusselator_f(x, y, t)
    du[i,j,2] = alpha*(u[im1,j,2] + u[ip1,j,2] + u[i,jp1,2] + u[i,jm1,2] - 4u[i,j,2]) +
                A*u[i,j,1] - u[i,j,1]^2*u[i,j,2]
    end
end
p = (3.4, 1., 10., step(xyd_brusselator))

function init_brusselator_2d(xyd)
  N = length(xyd)
  u = zeros(N, N, 2)
  for I in CartesianIndices((N, N))
    x = xyd[I[1]]
    y = xyd[I[2]]
    u[I,1] = 22*(y*(1-y))^(3/2)
    u[I,2] = 27*(x*(1-x))^(3/2)
  end
  u
end
u0 = init_brusselator_2d(xyd_brusselator)

using SparsityDetection, SparseArrays
input = rand(N,N,2)
output = similar(input)
sparsity_pattern = sparsity!(brusselator_2d_loop,output,input,p,0.0)
jac_sparsity = Float64.(sparse(sparsity_pattern))

using SparseDiffTools
colorvec = matrix_colors(jac_sparsity)
@show maximum(colorvec) # maximum(colorvec) = 12

f = ODEFunction(brusselator_2d_loop;jac_prototype=jac_sparsity,
                                    colorvec=colorvec)
prob_ode_brusselator_2d_sparse = ODEProblem(f,
                                     init_brusselator_2d(xyd_brusselator),
                                     (0.,11.5),p)

using BenchmarkTools
println("Rodas5")
@btime solve(prob_ode_brusselator_2d_sparse,Rodas5(),save_everystep=false)

import Pardiso
println("Rodas5 MKLPardiso")
@btime solve(prob_ode_brusselator_2d_sparse,Rodas5(linsolve = DiffEqBase.MKLPardisoFactorize()),save_everystep=false)

println("TRBDF2")
@btime solve(prob_ode_brusselator_2d_sparse,TRBDF2(),save_everystep=false)
println("TRBDF2 MKLPardiso")
@btime solve(prob_ode_brusselator_2d_sparse,TRBDF2(linsolve = DiffEqBase.MKLPardisoFactorize()),save_everystep=false)

println("KenCarp4")
@btime solve(prob_ode_brusselator_2d_sparse,KenCarp4(),save_everystep=false)
println("KenCarp4 MKLPardiso")
@btime solve(prob_ode_brusselator_2d_sparse,KenCarp4(linsolve = DiffEqBase.MKLPardisoFactorize()),save_everystep=false)

using Sundials
println("CVODE with GMRES")
@btime solve(prob_ode_brusselator_2d_sparse,CVODE_BDF(linear_solver=:GMRES),save_everystep=false)
```

```julia
Rodas5
  39.038 s (142319 allocations: 10.10 GiB)
Rodas5 MKLPardiso
  30.516 s (156209 allocations: 2.44 GiB)
TRBDF2
  33.969 s (143166 allocations: 8.13 GiB)
TRBDF2 MKLPardiso
  8.292 s (138801 allocations: 882.89 MiB)
KenCarp4
  37.745 s (144823 allocations: 6.79 GiB)
KenCarp4 MKLPardiso
  14.636 s (146130 allocations: 1.62 GiB)
CVODE with GMRES
  20.644 s (185419 allocations: 12.25 MiB)
```

And that's with the Jacobian like:

```
32768×32768 SparseMatrixCSC{Bool,Int64} with 196608 stored entries
```

**Comment by ChrisRackauckas** [comment]
Also added a quick interface over the non-MKL Pardiso:

```julia
@btime solve(prob_ode_brusselator_2d_sparse,TRBDF2(linsolve = DiffEqBase.PardisoFactorize()),save_everystep=false)

@btime solve(prob_ode_brusselator_2d_sparse,TRBDF2(linsolve = DiffEqBase.PardisoIterate()),save_everystep=false)
```

Now I just need to figure out how to install that in order to time it.

**Pull request merged**
