### PR TITLE
No recompile ODE setup

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
```julia
using OrdinaryDiffEq

# First time 

function lorenz(du,u,p,t)
  du[1] = 10.0(u[2]-u[1])
  du[2] = u[1]*(28.0-u[3]) - u[2]
  du[3] = u[1]*u[2] - (8/3)*u[3]
end
u0 = [1.0;0.0;0.0]
tspan = (0.0,100.0)
prob = ODEProblem{true,false}(lorenz,u0,tspan)
@time sol = solve(prob,Tsit5())

#6.820159 seconds (16.06 M allocations: 800.508 MiB, 8.44% gc time)

# Enable No-Recompile Mode

function lorenz2(du,u,p,t)
  du[1] = 10.0(u[2]-u[1])
  du[2] = u[1]*(28.0-u[3]) - u[2]
  du[3] = u[1]*u[2] - (8/3)*u[3]
end
prob = ODEProblem{true,false}(lorenz2,u0,tspan)
@time sol = solve(prob,Tsit5())

#0.004248 seconds (12.96 k allocations: 1.375 MiB)

using BenchmarkTools

@btime sol = solve(prob,Tsit5())

# 1.146 ms (12961 allocations: 1.37 MiB)

# Disable No-Recompile Mode

function lorenz3(du,u,p,t)
  du[1] = 10.0(u[2]-u[1])
  du[2] = u[1]*(28.0-u[3]) - u[2]
  du[3] = u[1]*u[2] - (8/3)*u[3]
end
prob = ODEProblem{true}(lorenz3,u0,tspan)
@time sol = solve(prob,Tsit5())

#1.839436 seconds (3.97 M allocations: 190.402 MiB, 4.78% gc time)

@btime sol = solve(prob,Tsit5())

# 1.078 ms (12963 allocations: 1.37 MiB)
```

@YingboMa . 

Note that this isn't safe to use without `remake` making sure types in the FunctionWrapper change whenever changing the types, which is important when doing things like AD. But this is what would be required for static compilation to be done completely.

### CODE REVIEW

**Comment by kanav99** [comment]
Allocations are negligible now, but time worries me:
```
  5.435981 seconds (18.04 M allocations: 899.935 MiB, 7.41% gc time)
  0.001436 seconds (12.96 k allocations: 1.375 MiB)
  1.173 ms (12961 allocations: 1.37 MiB)
  1.515501 seconds (4.08 M allocations: 194.177 MiB, 3.34% gc time)
  1.103 ms (12963 allocations: 1.37 MiB)
```
Thats about 6% regression in avg time. 
Also just noticed: 12.6k avg allocations look scary to me.

**Comment by ChrisRackauckas** [comment]
My hypothesis is that this is constant, so 6% is the worst case scenario. Try a stiff problem, and a larger non-stiff problem.

**Comment by kanav99** [comment]
No this is not constant, I get this on a stiff problem:
```
 18.188528 seconds (77.34 M allocations: 6.819 GiB, 56.00% gc time)
 49.572909 seconds (98.26 M allocations: 8.789 GiB, 80.71% gc time)
  34.417 ns (0 allocations: 0 bytes)
101.994709 seconds (104.19 M allocations: 9.071 GiB, 89.10% gc time)
  36.123 ns (0 allocations: 0 bytes)
```
Again nearly 6%. Problem is VanDarPol2 from DiffEqBenchmarks.

**Comment by kanav99** [comment]
Need to investigate strange benchmarks (for some stiff problem the time for recompilation is even higher, MWE can be found [here](https://gist.github.com/kanav99/570edb1df03b0ad8c9037eccecb660e4)).

**Comment by ChrisRackauckas** [comment]
What do you mean? That looks fine?

**Comment by kanav99** [comment]
In the above (https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/208#issuecomment-495999176) benchmarks you can see time for second compilation (49s) is larger than first one (18s)

**Comment by ChrisRackauckas** [comment]
What are you running for that? Different from the Gist?

**Comment by kanav99** [comment]
No I am running the same gist. Are you getting different results?

**Comment by kanav99** [comment]
Results of gist:
```
 22.742407 seconds (91.39 M allocations: 7.514 GiB, 49.59% gc time)
 51.102763 seconds (98.26 M allocations: 8.789 GiB, 81.06% gc time)
  68.667 s (98255922 allocations: 8.79 GiB)
 68.912910 seconds (102.43 M allocations: 8.983 GiB, 84.40% gc time)
  64.044 s (98255925 allocations: 8.79 GiB)
```

**Pull request merged**
