### PR TITLE
More API docs

### PR DESCRIPTION
**Pull request by jlumpe**
* Added docstring stubs for most types that don't have them
* Expanded documentation skeleton significantly. Didn't add much text, but types/functions are organized logically over pages, headings, and subheadings. Now covers a large majority of types and a good number of functions.
* Added a few actual docstrings
* Fixed up a few issues with existing docstrings

There is very little actual content added, but defining the overall structure should further lower the barrier for people who actually know the code to contribute to the documentation.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
I think the docstrings are fine, but I am not sure having a separate docs is necessary or even a good thing. Adding an API tab to the bottom of the DiffEqDocs may be all that's needed.

On Wed, Oct 23, 2019, 4:51 AM Michael Jared Lumpe <notifications@github.com [mailto:notifications@github.com]> wrote:

* Added docstring stubs for most types that don't have them
* Expanded documentation skeleton significantly. Didn't add much text, but types/functions are organized logically over pages, headings, and subheadings. Now covers a large majority of types and a good number of functions.
* Added a few actual docstrings
* Fixed up a few issues with existing docstrings
There is very little actual content added, but defining the overall structure should further lower the barrier for people who actually know the code to contribute to the documentation.
You can view, comment on, or merge this pull request online at:
  https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362 [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362]
Commit Summary
* Add docstring stubs for most remaining types, normalize existing
* Complete most of API documentation skeleton
* Add some function/macro docstrings
* Updates/fixes to existing docstrings
File Changes
* M docs/make.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-0] (12)
* A docs/src/api/callbacks.md [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-1] (23)
* A docs/src/api/data_arrays.md [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-2] (13)
* A docs/src/api/de_types.md [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-3] (219)
* A docs/src/api/ensembles.md [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-4] (86)
* M docs/src/api/functions.md [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-5] (40)
* A docs/src/api/integrators.md [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-6] (61)
* A docs/src/api/interpolation.md [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-7] (20)
* A docs/src/api/noise.md [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-8] (6)
* A docs/src/api/operators.md [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-9] (28)
* M docs/src/api/overview.md [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-10] (36)
* M docs/src/api/problems.md [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-11] (93)
* A docs/src/api/solutions.md [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-12] (20)
* A docs/src/api/solvers.md [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-13] (36)
* A docs/src/api/utility.md [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-14] (15)
* M src/DiffEqBase.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-15] (129)
* M src/callbacks.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-16] (26)
* M src/destats.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-17] (5)
* M src/diffeqfunction.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-18] (7)
* M src/ensemble/basic_ensemble_solve.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-19] (29)
* M src/ensemble/ensemble_problems.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-20] (5)
* M src/ensemble/ensemble_solutions.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-21] (15)
* M src/integrator_interface.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-22] (5)
* M src/interpolation.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-23] (21)
* M src/operators/basic_operators.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-24] (8)
* M src/problems/analytical_problems.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-25] (5)
* M src/problems/basic_problems.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-26] (15)
* M src/problems/bvp_problems.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-27] (22)
* M src/problems/dae_problems.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-28] (5)
* M src/problems/dde_problems.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-29] (5)
* M src/problems/noise_problems.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-30] (5)
* M src/problems/ode_problems.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-31] (2)
* M src/problems/pde_problems.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-32] (5)
* M src/problems/problem_traits.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-33] (2)
* M src/problems/rode_problems.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-34] (5)
* M src/problems/sdde_problems.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-35] (7)
* M src/problems/sde_problems.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-36] (21)
* M src/problems/steady_state_problems.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-37] (2)
* M src/solutions/basic_solutions.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-38] (5)
* M src/solutions/dae_solutions.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-39] (5)
* M src/solutions/ode_solutions.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-40] (5)
* M src/solutions/rode_solutions.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-41] (5)
* M src/solutions/steady_state_solutions.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-42] (7)
* M src/solve.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-43] (12)
* M src/tableaus.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-44] (4)
* M src/utils.jl [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362/files#diff-45] (40)
Patch Links:
* https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362.patch [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362.patch]
* https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362.diff [https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/362.diff]

**Comment by jlumpe** [comment]
Yeah, with my initial PR adding the documentation I had planned that it was temporary and should eventually be moved into either `DiffEqDocs` or `DiffEqDevDocs`. If you think one of those is appropriate I can keep the docstrings and do a separate PR for the documentation pages.

**Comment by ChrisRackauckas** [comment]
I think they should go in the regular docs. We should have an API section, if only for making sure everything is searchable.

**Comment by jlumpe** [comment]
Removed `docs/` directory and will make a separate commit to `DiffEqDocs`. I would have liked to keep the documentation pages stored in this repo and just import them from `DiffEqDocs` so people wouldn't have to create a separate PR to document their changes, but it seems `Documenter.jl` doesn't support using external files.

**Comment by jlumpe** [comment]
Also removed all TODOs in the docstring stubs so they are more suitable for inclusion in the public documentation.

**Pull request merged**
