### PR TITLE
Add matrix free interface for Jacobian

### PR DESCRIPTION
**Pull request by YingboMa**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Can't this be done with just a Jacobian type that defines `mul!`?

**Comment by YingboMa** [comment]
Maybe we can add a `DiffEqOperators.MatrixFreeOperator`?

**Comment by ChrisRackauckas** [comment]
Yes that would be a good idea, one that makes it easy to define one from a multiplication function.

**Comment by YingboMa** [comment]
On another thought, maybe a much easier way to do it is to differentiate `jac(u, p, t)` and `jac(v, u, p, t)` for the out-of-place version and similarly for the in-place ones.

**Comment by ChrisRackauckas** [comment]
Handled alternatively.

**Pull request closed without merging**
