### PR TITLE
Safer epsilon in callback and handle callback switch off

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
We may want to try/catch using a dual number as well?

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@lstagner see if this branch fixes your double callback issue.

**Comment by lstagner** [comment]
I still run into this issue. Is it possible to just handle the error in a reasonable way and just emit a warning instead of erroring out?

**Comment by ChrisRackauckas** [comment]
No, because the error is given to avoid an infinite loop. Is there any way I or @kanav99 can see this example? I'm curious how it's coming up.

**Comment by lstagner** [comment]
Sorry for the delay I was working on a rewrite i was hoping will solve the issue. Unfortunately it didn't fix the issue. 

Here is a MWE. 
[callback_mwe.zip](https://github.com/JuliaDiffEq/DiffEqBase.jl/files/3341037/callback_mwe.zip)

**Comment by kanav99** [comment]
@lstagner I get these warnings and errors on my PC - 
```julia-repl
julia> @load "equilibrium.jld2"
┌ Warning: type OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}} does not exist in workspace; reconstructing
└ @ JLD2 ~/.julia/packages/JLD2/KjBIK/src/data.jl:1153
┌ Warning: type Interpolations.BSplineInterpolation{Float64,2,getfield(JLD2.ReconstructedTypes, Symbol("##OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}#363")),Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}},Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}} does not exist in workspace; reconstructing
└ @ JLD2 ~/.julia/packages/JLD2/KjBIK/src/data.jl:1153
┌ Warning: type Interpolations.ScaledInterpolation{Float64,2,getfield(JLD2.ReconstructedTypes, Symbol("##Interpolations.BSplineInterpolation{Float64,2,getfield(JLD2.ReconstructedTypes, Symbol("##OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}#363")),Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}},Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}}#364")),Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}},Tuple{StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}} does not exist in workspace; reconstructing
└ @ JLD2 ~/.julia/packages/JLD2/KjBIK/src/data.jl:1153
┌ Warning: type Interpolations.Extrapolation{Float64,2,getfield(JLD2.ReconstructedTypes, Symbol("##Interpolations.ScaledInterpolation{Float64,2,getfield(JLD2.ReconstructedTypes, Symbol("##Interpolations.BSplineInterpolation{Float64,2,getfield(JLD2.ReconstructedTypes, Symbol("##OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}#363")),Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}},Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}}#364")),Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}},Tuple{StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}#365")),Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}},Interpolations.Flat{Nothing}} does not exist in workspace; reconstructing
└ @ JLD2 ~/.julia/packages/JLD2/KjBIK/src/data.jl:1153
┌ Warning: type OffsetArrays.OffsetArray{Float64,1,Array{Float64,1}} does not exist in workspace; reconstructing
└ @ JLD2 ~/.julia/packages/JLD2/KjBIK/src/data.jl:1153
┌ Warning: type Interpolations.BSplineInterpolation{Float64,1,getfield(JLD2.ReconstructedTypes, Symbol("##OffsetArrays.OffsetArray{Float64,1,Array{Float64,1}}#367")),Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}},Tuple{Base.OneTo{Int64}}} does not exist in workspace; reconstructing
└ @ JLD2 ~/.julia/packages/JLD2/KjBIK/src/data.jl:1153
┌ Warning: type Interpolations.ScaledInterpolation{Float64,1,getfield(JLD2.ReconstructedTypes, Symbol("##Interpolations.BSplineInterpolation{Float64,1,getfield(JLD2.ReconstructedTypes, Symbol("##OffsetArrays.OffsetArray{Float64,1,Array{Float64,1}}#367")),Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}},Tuple{Base.OneTo{Int64}}}#368")),Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}},Tuple{StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}} does not exist in workspace; reconstructing
└ @ JLD2 ~/.julia/packages/JLD2/KjBIK/src/data.jl:1153
┌ Warning: type Interpolations.Extrapolation{Float64,1,getfield(JLD2.ReconstructedTypes, Symbol("##Interpolations.ScaledInterpolation{Float64,1,getfield(JLD2.ReconstructedTypes, Symbol("##Interpolations.BSplineInterpolation{Float64,1,getfield(JLD2.ReconstructedTypes, Symbol("##OffsetArrays.OffsetArray{Float64,1,Array{Float64,1}}#367")),Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}},Tuple{Base.OneTo{Int64}}}#368")),Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}},Tuple{StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}#369")),Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}},Interpolations.Flat{Nothing}} does not exist in workspace; reconstructing
└ @ JLD2 ~/.julia/packages/JLD2/KjBIK/src/data.jl:1153
┌ Warning: type parameters for AxisymmetricEquilibrium{Float64,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},getfield(JLD2.ReconstructedTypes, Symbol("##Interpolations.Extrapolation{Float64,2,getfield(JLD2.ReconstructedTypes, Symbol("##Interpolations.ScaledInterpolation{Float64,2,getfield(JLD2.ReconstructedTypes, Symbol("##Interpolations.BSplineInterpolation{Float64,2,getfield(JLD2.ReconstructedTypes, Symbol("##OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}#363")),Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}},Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}}#364")),Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}},Tuple{StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}#365")),Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}},Interpolations.Flat{Nothing}}#366")),getfield(JLD2.ReconstructedTypes, Symbol("##Interpolations.Extrapolation{Float64,1,getfield(JLD2.ReconstructedTypes, Symbol("##Interpolations.ScaledInterpolation{Float64,1,getfield(JLD2.ReconstructedTypes, Symbol("##Interpolations.BSplineInterpolation{Float64,1,getfield(JLD2.ReconstructedTypes, Symbol("##OffsetArrays.OffsetArray{Float64,1,Array{Float64,1}}#367")),Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}},Tuple{Base.OneTo{Int64}}}#368")),Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}},Tuple{StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}#369")),Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}},Interpolations.Flat{Nothing}}#370"))} do not match type AxisymmetricEquilibrium in workspace; reconstructing
└ @ JLD2 ~/.julia/packages/JLD2/KjBIK/src/data.jl:1133
2-element Array{Symbol,1}:
 :MB  
 :wall
julia> gcp = GCParticle{Float64}(65.51724137931035, -0.03413793103448276, 1.6985034642857142, -0.7070365595918368, 3.344496968928368e-27, 1)
GCParticle{Float64}(65.51724137931035, -0.03413793103448276, 1.6985034642857142, -0.7070365595918368, 3.344496968928368e-27, 1)

julia> o=get_orbit(MB, gcp, vacuum=true, verbose=true, maxiter=1)
ERROR: MethodError: no method matching get_orbit(::getfield(JLD2.ReconstructedTypes, Symbol("##AxisymmetricEquilibrium{Float64,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},getfield(JLD2.ReconstructedTypes, Symbol("##Interpolations.Extrapolation{Float64,2,getfield(JLD2.ReconstructedTypes, Symbol("##Interpolations.ScaledInterpolation{Float64,2,getfield(JLD2.ReconstructedTypes, Symbol("##Interpolations.BSplineInterpolation{Float64,2,getfield(JLD2.ReconstructedTypes, Symbol("##OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}#363")),Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}},Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}}#364")),Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}},Tuple{StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}#365")),Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}},Interpolations.Flat{Nothing}}#366")),getfield(JLD2.ReconstructedTypes, Symbol("##Interpolations.Extrapolation{Float64,1,getfield(JLD2.ReconstructedTypes, Symbol("##Interpolations.ScaledInterpolation{Float64,1,getfield(JLD2.ReconstructedTypes, Symbol("##Interpolations.BSplineInterpolation{Float64,1,getfield(JLD2.ReconstructedTypes, Symbol("##OffsetArrays.OffsetArray{Float64,1,Array{Float64,1}}#367")),Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}},Tuple{Base.OneTo{Int64}}}#368")),Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}},Tuple{StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}#369")),Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}},Interpolations.Flat{Nothing}}#370"))}#371")), ::GCParticle{Float64}; vacuum=true, verbose=true, maxiter=1)
Closest candidates are:
  get_orbit(::AxisymmetricEquilibrium, ::GCParticle; kwargs...) at /home/kanav/.julia/packages/GuidingCenterOrbits/sUShu/src/orbit.jl:305
Stacktrace:
 [1] top-level scope at none:0


```

**Comment by kanav99** [comment]
I have some questions about the problem you are solving - 
1. Is the `dt` involved negative?
2. How does the `condition` function look like? Is there some kind of discontinuity there?
If there is an issue opened which explains it the whole, please do post the link

**Comment by ChrisRackauckas** [comment]
Do we have a test with negative `dt` at all? That could definitely be the issue. Some `dt`s probably need a `tdir` on it.

**Comment by lstagner** [comment]
1. The `dt` that is most commonly used is positive but there are use cases where negative `dt` would be used, such as backtracking a particle from some position. Negative `dt` shouldn't be the problem here unless the internal callback code uses it.

2. There are multiple callbacks that are used. For the example I gave there are three
    * [A simple out-of-bounds check](https://github.com/JuliaFusion/GuidingCenterOrbits.jl/blob/master/src/callbacks.jl#L53)
    * [A callback that checks whether a particle has completed an orbit](https://github.com/JuliaFusion/GuidingCenterOrbits.jl/blob/master/src/callbacks.jl#L24)
    * [A callback that finds where the particle changes direction](https://github.com/JuliaFusion/GuidingCenterOrbits.jl/blob/master/src/callbacks.jl#L1)

There shouldn't be any discontinuities

**Pull request merged**
